option(ADH_ENABLE_SANITIZERS "Enable sanitizers for Debug builds" OFF)

function(adhoc_project_options target)
    target_compile_features(${target} PRIVATE cxx_std_23)
    set_target_properties(${target} PROPERTIES CXX_EXTENSIONS OFF)
    if(MSVC)
        target_compile_options(${target} PRIVATE /W4 /utf-8 /wd4324)
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra)
    endif()

    if(NOT ADH_ENABLE_SANITIZERS)
        return()
    endif()

    if(MSVC)
        if(CMAKE_CXX_FLAGS_DEBUG MATCHES "/RTC|/ZI")
            message(WARNING "ASan is incompatible with MSVC /RTC or /ZI; keeping normal Debug checks.")
            return()
        endif()
        set(sanitizer_compile_options /fsanitize=address)
        set(sanitizer_link_options /INCREMENTAL:NO)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "^(GNU|Clang|AppleClang)$" AND (APPLE OR CMAKE_SYSTEM_NAME STREQUAL "Linux"))
        set(sanitizer_compile_options -fsanitize=address,undefined -fno-sanitize=vptr -fno-omit-frame-pointer -fno-sanitize-recover=undefined)
        set(sanitizer_link_options -fsanitize=address,undefined)
    else()
        message(WARNING "Sanitizers are unavailable for this platform/compiler.")
        return()
    endif()

    include(CheckCXXSourceCompiles)
    string(JOIN " " CMAKE_REQUIRED_FLAGS ${sanitizer_compile_options})
    set(CMAKE_REQUIRED_LINK_OPTIONS ${sanitizer_link_options})
    set(CMAKE_TRY_COMPILE_CONFIGURATION Debug)
    set(CMAKE_TRY_COMPILE_TARGET_TYPE EXECUTABLE)
    check_cxx_source_compiles("int main() { return 0; }" ADH_HAS_SANITIZERS)
    if(ADH_HAS_SANITIZERS)
        target_compile_options(${target} PRIVATE "$<$<CONFIG:Debug>:${sanitizer_compile_options}>")
        target_link_options(${target} PRIVATE "$<$<CONFIG:Debug>:${sanitizer_link_options}>")
        message(STATUS "Debug sanitizers enabled for ${target}")
    else()
        message(WARNING "Sanitizers failed the compiler/linker check; keeping normal Debug checks.")
    endif()
endfunction()
